### Testar conexão com o servidor
GET http://localhost:3000/


### EMPLOYEE
### Criar um funcionário
POST http://localhost:3000/employee
Content-Type: application/json

{
  "name": "Janderson Vilas Boas",
  "estimatedHours": 12 
}

### Listar todos os funcionários
GET http://localhost:3000/employee

### Listar um funcionário
GET http://localhost:3000/employee/1

### Atualizar um funcionário
PUT http://localhost:3000/employee/1

{
  "name": "Théo José",
  "estimatedHours": 12,
  "squadId": 2
}

### Deletar um funcionário
DELETE http://localhost:3000/employee/1






### SQUAD
### Criar um squad
POST http://localhost:3000/squad
Content-Type: application/json

{
  "name": "Backe-end"
}

### Listar todos os squads
GET http://localhost:3000/squad

### Listar um squad
GET http://localhost:3000/squad/1

### Atualizar um squad
PUT http://localhost:3000/squad/1

{
  "name": "Squad 1"
}

### Deletar um squad
DELETE http://localhost:3000/squad/2


### REPORT
### Criar um report
POST http://localhost:3000/report
Content-Type: application/json

{
  "employeeId": 1,
  "description": "Tela de SIGNUP",
  "spentHours": 8
}

### Listar todos os reports
GET http://localhost:3000/report

### Listar um report
GET http://localhost:3000/report/1

### Atualizar um report
PUT http://localhost:3000/report/1

{
  "employeeId": 1,
  "description": "Trabalho de backend",
  "spentHours": 8
}

### Deletar um report
DELETE http://localhost:3000/report/1

```



### Listar horas trabalhadas
GET http://localhost:3000/squad/5/report

###  Procurar por squad
GET http://localhost:3000/squad/2/report?employeeId=1





###  Listar horas trabalhadas por período
GET http://localhost:3000/report/1?startDate=2021-09-01&endDate=2021-09-30


### Listar horas trabalhadas por período
GET http://localhost:3000/report/1?startDate=2021-09-01&endDate=2021-09-30


```




